const { app, BrowserWindow, ipcMain, dialog, clipboard, shell } = require('electron');
const path = require('path');
const fs = require('fs');
const https = require('https');
const http = require('http');
const { spawn } = require('child_process');
const APP_VERSION = '5.0.20';
let mainWindow;
function dataDir(){ return path.join(app.getPath('appData'),'KaserPrinting','PDFPrintCalculator'); }
function dataPath(){ return path.join(dataDir(),'data.json'); }
const defaults={store_name:'KASER PRINTING',store_address:'',store_phone:'',logo_path:'',footer:'Terima kasih telah menggunakan jasa kami 🙏',price_bw:'500',price_warna:'1000',sensitivity:'5'};
function ensureData(){ fs.mkdirSync(dataDir(),{recursive:true}); if(!fs.existsSync(dataPath())) fs.writeFileSync(dataPath(),JSON.stringify({settings:defaults,transactions:[]},null,2),'utf8'); }
function loadData(){ ensureData(); try { const d=JSON.parse(fs.readFileSync(dataPath(),'utf8')); d.settings={...defaults,...(d.settings||{})}; d.transactions=Array.isArray(d.transactions)?d.transactions:[]; return d; } catch { return {settings:{...defaults},transactions:[]}; } }
function saveData(d){ ensureData(); const tmp=dataPath()+'.tmp'; fs.writeFileSync(tmp,JSON.stringify(d,null,2),'utf8'); fs.renameSync(tmp,dataPath()); }
function rupiah(v){return 'Rp '+Number(v||0).toLocaleString('id-ID');}
function escHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function imageDataUri(p){try{if(!p||!fs.existsSync(p))return '';const ext=path.extname(p).toLowerCase();const mime=ext==='.jpg'||ext==='.jpeg'?'image/jpeg':ext==='.webp'?'image/webp':'image/png';return `data:${mime};base64,${fs.readFileSync(p).toString('base64')}`;}catch{return '';}}
function nextInvoice(d){const prefix='KP-'+new Date().toISOString().slice(2,10).replace(/-/g,'')+'-';let max=0;for(const r of d.transactions){if(String(r.invoice||'').startsWith(prefix)){const n=parseInt(String(r.invoice).split('-').pop(),10)||0;max=Math.max(max,n);}}return prefix+String(max+1).padStart(3,'0');}
function invoiceText(d,settings){const dt=new Date(d.created_at).toLocaleString('id-ID',{hour12:false});return `*${settings.store_name||'KASER PRINTING'}*\n${settings.store_address||''}\n${settings.store_phone||''}\nNOTA PENJUALAN\n━━━━━━━━━━━━━━━━━━━━\nNo. Nota: ${d.invoice}\nTanggal: ${dt}\nNama: ${d.customer}\nFile: ${d.filename}\n\n⚫ Hitam Putih: ${d.bw} × ${rupiah(d.price_bw)} = ${rupiah(d.bw*d.price_bw)}\n🎨 Warna: ${d.warna} × ${rupiah(d.price_warna)} = ${rupiah(d.warna*d.price_warna)}\nSubtotal: ${rupiah(d.subtotal)}\nDiskon: ${rupiah(d.discount)}\n━━━━━━━━━━━━━━━━━━━━\n*TOTAL: ${rupiah(d.total)}*\n${d.notes?`Keterangan: ${d.notes}\n`:''}${settings.footer||'Terima kasih 🙏'}`;}
async function printPdfNative(filePath){if(!filePath||!fs.existsSync(filePath))return{ok:false,error:'File PDF tidak ditemukan.'};const win=new BrowserWindow({show:true,width:1000,height:800,autoHideMenuBar:true,backgroundColor:'#fff',webPreferences:{plugins:true,sandbox:true}});try{const fileUrl='file:///'+filePath.replace(/\\/g,'/').split('/').map((part,i)=>i===0?part:encodeURIComponent(part)).join('/');await win.loadURL(fileUrl);await new Promise(r=>setTimeout(r,700));return await new Promise(resolve=>win.webContents.print({silent:false,printBackground:true,margins:{marginType:'default'}},(success,reason)=>{if(success)resolve({ok:true});else resolve({ok:false,error:reason||'Dialog printer dibatalkan atau gagal.'});}));}catch(e){return{ok:false,error:'Gagal menyiapkan PDF untuk dicetak: '+e.message}}finally{setTimeout(()=>{if(!win.isDestroyed())win.close()},700);}}
function createWindow(){mainWindow=new BrowserWindow({width:1440,height:900,minWidth:1100,minHeight:700,backgroundColor:'#11131a',title:'Kaser Printing PDF Calculator',icon:path.join(__dirname,'..','build','icon.ico'),autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});mainWindow.loadFile(path.join(__dirname,'index.html'));mainWindow.removeMenu();mainWindow.setMenuBarVisibility(false);if(!app.isPackaged)mainWindow.webContents.openDevTools({mode:'detach'});}
app.whenReady().then(()=>{ensureData();createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow();});});
ipcMain.handle('pick-pdf',async()=>{const r=await dialog.showOpenDialog(mainWindow,{properties:['openFile'],filters:[{name:'PDF Files',extensions:['pdf']}]});return r.canceled?null:r.filePaths[0];});
ipcMain.handle('pick-logo',async()=>{const r=await dialog.showOpenDialog(mainWindow,{properties:['openFile'],filters:[{name:'Image Files',extensions:['png','jpg','jpeg','webp']}]});return r.canceled?null:r.filePaths[0];});
ipcMain.handle('save-logo',async(_,source)=>{try{if(!source||!fs.existsSync(source))return{ok:false,error:'File logo tidak ditemukan.'};ensureData();const ext=path.extname(source).toLowerCase()||'.png';const dest=path.join(dataDir(),'store-logo'+ext);for(const f of fs.readdirSync(dataDir()))if(/^store-logo\./i.test(f)&&path.join(dataDir(),f)!==dest){try{fs.unlinkSync(path.join(dataDir(),f));}catch{}}fs.copyFileSync(source,dest);return{ok:true,path:dest};}catch(e){return{ok:false,error:e.message}}});
ipcMain.handle('read-file',async(_,p)=>{try{return{ok:true,data:fs.readFileSync(p).toString('base64')}}catch(e){return{ok:false,error:e.message}}});
ipcMain.handle('get-settings',()=>{const d=loadData();return{ok:true,settings:d.settings}});
ipcMain.handle('save-settings',(_,s)=>{const d=loadData();d.settings={...d.settings,...s};saveData(d);return{ok:true,settings:d.settings}});
ipcMain.handle('create-transaction',(_,x)=>{const d=loadData();const subtotal=Math.max(0,Number(x.subtotal)||0),discount=Math.max(0,Number(x.discount)||0),total=Math.max(0,subtotal-discount);const r={invoice:nextInvoice(d),created_at:new Date().toISOString(),customer:x.customer||'Pelanggan',phone:x.phone||'',filename:x.filename||'-',bw:Number(x.bw)||0,warna:Number(x.warna)||0,price_bw:Number(x.price_bw)||500,price_warna:Number(x.price_warna)||1000,subtotal,discount,total,paid:Number(x.paid)||0,change:(Number(x.paid)||0)-total,notes:x.notes||''};d.transactions.push(r);saveData(d);return{ok:true,invoice:r.invoice}});
ipcMain.handle('get-invoice',(_,inv)=>{const d=loadData();const r=d.transactions.find(x=>x.invoice===inv);if(!r)return{ok:false,error:'Nota tidak ditemukan'};return{ok:true,data:r,text:invoiceText(r,d.settings)}});
ipcMain.handle('get-history',(_,q='')=>{const d=loadData(),needle=String(q||'').toLowerCase();const rows=d.transactions.filter(r=>!needle||[r.invoice,r.customer,r.filename].some(v=>String(v||'').toLowerCase().includes(needle))).slice(-200).reverse();return{ok:true,rows}});
ipcMain.handle('backup-data',async()=>{ensureData();const stamp=new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14);const dest=path.join(dataDir(),'backups');fs.mkdirSync(dest,{recursive:true});const out=path.join(dest,`data_${stamp}.json`);fs.copyFileSync(dataPath(),out);return{ok:true,path:out}});
ipcMain.handle('write-file',async(_,x)=>{try{fs.mkdirSync(x.dir,{recursive:true});const p=path.join(x.dir,x.filename);fs.writeFileSync(p,Buffer.from(x.data,'base64'));return{ok:true,path:p}}catch(e){return{ok:false,error:e.message}}});
ipcMain.handle('save-png',async(_,x)=>{const r=await dialog.showSaveDialog(mainWindow,{defaultPath:x.filename,filters:[{name:'PNG Image',extensions:['png']}]});if(r.canceled)return null;fs.writeFileSync(r.filePath,Buffer.from(x.data,'base64'));return r.filePath;});
ipcMain.handle('choose-folder',async()=>{const r=await dialog.showOpenDialog(mainWindow,{properties:['openDirectory','createDirectory']});return r.canceled?null:r.filePaths[0]});
ipcMain.handle('copy',(_,text)=>{clipboard.writeText(text);return true});
ipcMain.handle('open-folder',(_,p)=>{shell.showItemInFolder(p);return true});
ipcMain.handle('app-info',()=>({version:APP_VERSION,dataDir:dataDir(),packaged:app.isPackaged,engine:'Electron only'}));
ipcMain.handle('print-pdf-native',async(_,filePath)=>{try{return await printPdfNative(filePath)}catch(e){return{ok:false,error:e.message}}});
function versionParts(v){return String(v||'0').replace(/^v/i,'').split('.').map(x=>parseInt(x,10)||0).slice(0,3).concat([0,0,0]).slice(0,3)}function isNewerVersion(a,b){const x=versionParts(a),y=versionParts(b);for(let i=0;i<3;i++){if(x[i]>y[i])return true;if(x[i]<y[i])return false}return false}
function updateConfigPath(){const p=path.join(process.resourcesPath,'update-config.json'),d=path.join(__dirname,'..','update-config.json');return fs.existsSync(p)?p:d}
function fetchJson(url,redirects=0){return new Promise((resolve,reject)=>{if(redirects>5)return reject(new Error('Terlalu banyak redirect.'));let client;try{client=new URL(url).protocol==='https:'?https:http}catch(e){return reject(e)}client.get(url,{headers:{'User-Agent':'Kaser-PDF-Calculator-Updater'}},res=>{if([301,302,303,307,308].includes(res.statusCode)&&res.headers.location){res.resume();return resolve(fetchJson(new URL(res.headers.location,url).toString(),redirects+1))}let body='';res.setEncoding('utf8');res.on('data',c=>body+=c);res.on('end',()=>res.statusCode>=200&&res.statusCode<300?resolve(JSON.parse(body)):reject(new Error(`HTTP ${res.statusCode}`))) }).on('error',reject)})}
ipcMain.handle('check-update',async()=>{try{const p=updateConfigPath();if(!fs.existsSync(p))return{ok:false,configured:false,error:'update-config.json tidak ditemukan.'};const cfg=JSON.parse(fs.readFileSync(p,'utf8'));if(!cfg.url)return{ok:false,configured:false};const remote=await fetchJson(cfg.url);const latest=remote.version||remote.latest||'';return{ok:true,latest,url:remote.downloadUrl||remote.url||cfg.downloadUrl,filename:remote.filename||cfg.filename,notes:remote.notes||'',updateAvailable:isNewerVersion(latest,APP_VERSION),version:latest}}catch(e){return{ok:false,error:e.message}}});
ipcMain.handle('download-update',async(_,x)=>{if(!x.url)return{ok:false,error:'URL update belum diatur.'};const out=path.join(app.getPath('temp'),String(x.filename||'Kaser-PDF-Calculator-Update.exe').replace(/[^a-zA-Z0-9._-]/g,'_'));const dl=(u,n=0)=>new Promise((resolve,reject)=>{if(n>5)return reject(new Error('Terlalu banyak redirect.'));let c;try{c=new URL(u).protocol==='https:'?https:http}catch(e){return reject(e)}c.get(u,{headers:{'User-Agent':'Kaser-PDF-Calculator-Updater'}},res=>{if([301,302,303,307,308].includes(res.statusCode)&&res.headers.location){res.resume();return resolve(dl(new URL(res.headers.location,u).toString(),n+1))}if(res.statusCode!==200){res.resume();return reject(new Error(`Download gagal (HTTP ${res.statusCode}).`))}const f=fs.createWriteStream(out);res.pipe(f);f.on('finish',()=>f.close(()=>resolve(out)));f.on('error',reject)}).on('error',reject)});try{return{ok:true,path:await dl(x.url)}}catch(e){return{ok:false,error:e.message}}});
ipcMain.handle('launch-update',async(_,x)=>{if(!x.path||!fs.existsSync(x.path))return{ok:false,error:'File update tidak ditemukan.'};try{const c=spawn(x.path,[],{detached:true,stdio:'ignore',windowsHide:false});c.unref();setTimeout(()=>app.quit(),500);return{ok:true}}catch(e){return{ok:false,error:e.message}}});
ipcMain.handle('pick-update',async()=>{const r=await dialog.showOpenDialog(mainWindow,{properties:['openFile'],filters:[{name:'Kaser Update ZIP',extensions:['zip']}]});return r.canceled?null:r.filePaths[0]});
ipcMain.handle('close-app',()=>app.quit());
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
